package codegen

import (
	"fmt"
	"strings"
)

// PresentationGenerator генератор presentation слоя
type PresentationGenerator struct {
	*BaseGenerator
}

// NewPresentationGenerator создает новый генератор presentation слоя
func NewPresentationGenerator(outputDir string) *PresentationGenerator {
	return &PresentationGenerator{
		BaseGenerator: NewBaseGenerator("presentation", outputDir),
	}
}

// Generate генерирует presentation слой
func (g *PresentationGenerator) Generate(spec *ParsedSpec, config *GeneratorConfig) error {
	if err := g.generateRESTHandler(spec, config); err != nil {
		return fmt.Errorf("failed to generate REST handler: %w", err)
	}

	if err := g.generateAPIExamples(spec, config); err != nil {
		return fmt.Errorf("failed to generate API examples: %w", err)
	}

	return nil
}

// generateRESTHandler генерирует REST handler
func (g *PresentationGenerator) generateRESTHandler(spec *ParsedSpec, config *GeneratorConfig) error {
	var content strings.Builder

	content.WriteString("// Code generated by potter-gen. DO NOT EDIT.\n\n")
	content.WriteString("package rest\n\n")
	content.WriteString("import (\n")
	content.WriteString("\t\"net/http\"\n")
	content.WriteString("\n")
	content.WriteString("\t\"github.com/gin-gonic/gin\"\n")
	content.WriteString(fmt.Sprintf("\t\"%s/application/command\"\n", config.ModulePath))
	content.WriteString(fmt.Sprintf("\t\"%s/application/query\"\n", config.ModulePath))
	content.WriteString("\t\"github.com/akriventsev/potter/framework/transport\"\n")
	content.WriteString(")\n\n")

	content.WriteString("// Handler REST API handler\n")
	content.WriteString("type Handler struct {\n")
	content.WriteString("\tcommandBus transport.CommandBus\n")
	content.WriteString("\tqueryBus   transport.QueryBus\n")
	content.WriteString("}\n\n")

	content.WriteString("// NewHandler создает новый REST handler\n")
	content.WriteString("func NewHandler(commandBus transport.CommandBus, queryBus transport.QueryBus) *Handler {\n")
	content.WriteString("\treturn &Handler{\n")
	content.WriteString("\t\tcommandBus: commandBus,\n")
	content.WriteString("\t\tqueryBus:   queryBus,\n")
	content.WriteString("\t}\n")
	content.WriteString("}\n\n")

	content.WriteString("// RegisterRoutes регистрирует все маршруты\n")
	content.WriteString("func (h *Handler) RegisterRoutes(router *gin.Engine) {\n")
	content.WriteString("\tapi := router.Group(\"/api/v1\")\n")
	content.WriteString("\t{\n")

	// Регистрация маршрутов для команд
	for _, cmd := range spec.Commands {
		resourceName := g.converter.ToSnakeCase(cmd.Aggregate)
		cmdName := g.converter.ToSnakeCase(cmd.Name)
		content.WriteString(fmt.Sprintf("\t\tapi.POST(\"/%s/%s\", h.%s)\n", resourceName, cmdName, cmd.Name))
	}

	// Регистрация маршрутов для запросов
	for _, query := range spec.Queries {
		resourceName := g.converter.ToSnakeCase(query.Name)
		content.WriteString(fmt.Sprintf("\t\tapi.GET(\"/%s\", h.%s)\n", resourceName, query.Name))
	}

	content.WriteString("\t}\n")
	content.WriteString("}\n\n")

	// Генерация handler методов для команд
	for _, cmd := range spec.Commands {
		content.WriteString(g.generateCommandHandler(cmd))
		content.WriteString("\n")
	}

	// Генерация handler методов для запросов
	for _, query := range spec.Queries {
		content.WriteString(g.generateQueryHandler(query))
		content.WriteString("\n")
	}

	path := "presentation/rest/handler.go"
	return g.writer.WriteFile(path, content.String())
}

// generateCommandHandler генерирует handler метод для команды
func (g *PresentationGenerator) generateCommandHandler(cmd CommandSpec) string {
	var builder strings.Builder

	builder.WriteString(fmt.Sprintf("// %s обрабатывает команду %s\n",
		strings.ToLower(cmd.Name), cmd.Name))
	builder.WriteString(fmt.Sprintf("func (h *Handler) %s(c *gin.Context) {\n", cmd.Name))
	builder.WriteString("\tvar req struct {\n")
	builder.WriteString("\t\t// Add request fields from command\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\tif err := c.ShouldBindJSON(&req); err != nil {\n")
	builder.WriteString("\t\tc.JSON(http.StatusBadRequest, gin.H{\"error\": err.Error()})\n")
	builder.WriteString("\t\treturn\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString(fmt.Sprintf("\tcmd := command.%sCommand{\n", cmd.Name))
	builder.WriteString("\t\t// Map request fields to command\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\tif err := h.commandBus.Send(c.Request.Context(), cmd); err != nil {\n")
	builder.WriteString("\t\tc.JSON(http.StatusInternalServerError, gin.H{\"error\": err.Error()})\n")
	builder.WriteString("\t\treturn\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\tc.JSON(http.StatusCreated, gin.H{\"message\": \"Command executed successfully\"})\n")
	builder.WriteString("}\n")

	return builder.String()
}

// generateQueryHandler генерирует handler метод для запроса
func (g *PresentationGenerator) generateQueryHandler(query QuerySpec) string {
	var builder strings.Builder

	builder.WriteString(fmt.Sprintf("// %s обрабатывает запрос %s\n",
		strings.ToLower(query.Name), query.Name))
	builder.WriteString(fmt.Sprintf("func (h *Handler) %s(c *gin.Context) {\n", query.Name))
	builder.WriteString(fmt.Sprintf("\tq := query.%sQuery{\n", query.Name))
	builder.WriteString("\t\t// Map query parameters to query\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\tresult, err := h.queryBus.Ask(c.Request.Context(), q)\n")
	builder.WriteString("\tif err != nil {\n")
	builder.WriteString("\t\tc.JSON(http.StatusNotFound, gin.H{\"error\": err.Error()})\n")
	builder.WriteString("\t\treturn\n")
	builder.WriteString("\t}\n\n")
	builder.WriteString("\tc.JSON(http.StatusOK, result)\n")
	builder.WriteString("}\n")

	return builder.String()
}

// generateAPIExamples генерирует примеры API
func (g *PresentationGenerator) generateAPIExamples(spec *ParsedSpec, _ *GeneratorConfig) error {
	// Генерация api_examples.md
	var mdContent strings.Builder
	mdContent.WriteString("# API Examples\n\n")
	mdContent.WriteString("Примеры использования API.\n\n")

	// Примеры для команд
	mdContent.WriteString("## Commands\n\n")
	for _, cmd := range spec.Commands {
		resourceName := g.converter.ToSnakeCase(cmd.Aggregate)
		cmdName := g.converter.ToSnakeCase(cmd.Name)
		mdContent.WriteString(fmt.Sprintf("### %s\n\n", cmd.Name))
		mdContent.WriteString("```bash\n")
		mdContent.WriteString(fmt.Sprintf("curl -X POST http://localhost:8080/api/v1/%s/%s \\\n",
			resourceName, cmdName))
		mdContent.WriteString("\t-H \"Content-Type: application/json\" \\\n")
		mdContent.WriteString("\t-d '{\n")
		mdContent.WriteString("\t\t\"field\": \"value\"\n")
		mdContent.WriteString("\t}'\n")
		mdContent.WriteString("```\n\n")
	}

	// Примеры для запросов
	mdContent.WriteString("## Queries\n\n")
	for _, query := range spec.Queries {
		resourceName := g.converter.ToSnakeCase(query.Name)
		mdContent.WriteString(fmt.Sprintf("### %s\n\n", query.Name))
		mdContent.WriteString("```bash\n")
		mdContent.WriteString(fmt.Sprintf("curl http://localhost:8080/api/v1/%s\n", resourceName))
		mdContent.WriteString("```\n\n")
	}

	if err := g.writer.WriteFile("api_examples.md", mdContent.String()); err != nil {
		return err
	}

	// Генерация api_examples.http
	var httpContent strings.Builder
	httpContent.WriteString("### API Examples\n\n")
	httpContent.WriteString("### Commands\n\n")
	for _, cmd := range spec.Commands {
		resourceName := g.converter.ToSnakeCase(cmd.Aggregate)
		cmdName := g.converter.ToSnakeCase(cmd.Name)
		httpContent.WriteString(fmt.Sprintf("POST http://localhost:8080/api/v1/%s/%s\n",
			resourceName, cmdName))
		httpContent.WriteString("Content-Type: application/json\n\n")
		httpContent.WriteString("{\n")
		httpContent.WriteString("\t\"field\": \"value\"\n")
		httpContent.WriteString("}\n\n")
	}

	httpContent.WriteString("### Queries\n\n")
	for _, query := range spec.Queries {
		resourceName := g.converter.ToSnakeCase(query.Name)
		httpContent.WriteString(fmt.Sprintf("GET http://localhost:8080/api/v1/%s\n\n", resourceName))
	}

	return g.writer.WriteFile("api_examples.http", httpContent.String())
}
